name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: CMAKE_BUILD_TYPE=Release
          build-args: --config Release
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.os }}
          path: |
            build\\**\\socli.exe
            build/bin/socli
  package:
    needs: cmake-build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact-ubuntu-latest
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-ubuntu-latest
      - name: Download build artifact-windows-latest
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-windows-latest
      - name: Extract build artifacts
        run: |
          mkdir -p build-artifacts
          unzip -q build-artifact-ubuntu-latest.zip -d build-artifacts
          unzip -q build-artifact-windows-latest.zip -d build-artifacts
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "**/socli*"
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}