name: PR build validation
on:
  pull_request:
    branches: [ main ]

jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: 'current'
          noNewCommitBehavior: 'current'
          prefix: 'dev'
      - name: Update version in CMakeLists.txt
        run: |
          sed -i "s/VERSION [0-9]\+\.[0-9]\+\.[0-9]\+/VERSION ${{ steps.semver.outputs.next }}/g" CMakeLists.txt
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: CMAKE_BUILD_TYPE=Release
          build-args: --config Release
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.os }}
          path: |
            build\\**\\socli.exe
            build/bin/socli

