name: Package Application with Pyinstaller

on:
  pull_request: ~

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0