name: PR build validation
on:
  pull_request:
    branches: [ main ]

jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: CMAKE_BUILD_TYPE=Release
          build-args: --config Release
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.os }}
          path: |
            build\\**\\socli*

